---
- name: Configure Linux VMs
  hosts: linux
  become: yes
  tasks:
    - name: Ensure NGINX is installed on Ubuntu
      apt:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Ensure HTTPD is installed on CentOS
      yum:
        name: httpd
        state: present
      when: ansible_distribution == "CentOS"

    - name: Print OS family and IP
      debug:
        msg: "This is a Linux machine: {{ ansible_distribution }} at {{ ansible_host }}"

---

- name: Configure Windows VMs
  hosts: windows
  gather_facts: no
  tasks:
    - name: Create Temp directory
      win_file:
        path: C:\Temp
        state: directory

    - name: Print confirmation
      win_command: hostname
      register: result

    - name: Show hostname
      debug:
        msg: "Windows hostname is {{ result.stdout }}"
