name: Deploy Azure VM with Ansible

on:
  push:
    branches:
      - main

jobs:
  terraform-ansible:
    runs-on: ubuntu-latest

    env:
      TF_VAR_ssh_public_key_path: ./id_rsa.pub

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y python3-pip jq
        pip3 install ansible

    - name: Generate SSH Key
      run: |
        ssh-keygen -t rsa -b 4096 -f id_rsa -N ""
        echo "SSH_PRIVATE_KEY<<EOF" >> $GITHUB_ENV
        cat id_rsa >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    - name: Terraform Apply
      working-directory: terraform
      run: terraform apply -auto-approve

    - name: Get Public IP
      id: tfoutput
      working-directory: terraform
      run: |
        terraform output -raw public_ip > ../ansible/vm_ip.txt

    - name: Generate Ansible Inventory (Single VM)
      run: |
        echo "[all]" > ansible/inventory
        echo "$(cat ansible/vm_ip.txt) ansible_user=azureuser ansible_ssh_private_key_file=./id_rsa" >> ansible/inventory

    - name: Run Ansible Playbook
      working-directory: ansible
      run: |
        echo "$SSH_PRIVATE_KEY" > id_rsa
        chmod 600 id_rsa
        ansible-playbook -i inventory playbook.yml
