name: Deploy Azure VM with Ansible

on:
  push:
    branches:
      - main

jobs:
  terraform-ansible:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    - name: Terraform Apply
      working-directory: terraform
      run: terraform apply -auto-approve

    - name: Get Public IP
      id: tfoutput
      working-directory: terraform
      run: |
        echo "PUBLIC_IP=$(terraform output -raw public_ip)" >> $GITHUB_ENV

    - name: Run Ansible Playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: ansible/playbook.yml
        inventory: |
          [all]
          ${{ env.PUBLIC_IP }} ansible_user=azureuser ansible_ssh_private_key_file=~/.ssh/id_rsa
