name: Terraform Outputs + Ansible Provision

on:
  workflow_dispatch:

jobs:
  provision-and-ansible:
    name: "Run Ansible on Self-hosted Runner"
    runs-on: [self-hosted, ansible]

    env:
      SSH_KEY_PATH: ~/.ssh/id_rsa
      LINUX_USER: azureuser
      WIN_USER: azureuser
      WIN_PASS: ${{ secrets.WIN_PASS }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Verify Ansible & Python
      run: |
        ansible --version
        python3 --version

    - name: Fetch Terraform Outputs from TFC
      env:
        TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
        TFC_WORKSPACE_ID: ${{ secrets.TFC_WORKSPACE_ID }}
      run: |
        curl -s \
          -H "Authorization: Bearer $TFC_TOKEN" \
          https://app.terraform.io/api/v2/workspaces/$TFC_WORKSPACE_ID/current-state-version/output-values \
          > ansible/terraform_output.json

    - name: Generate Dynamic Inventory
      working-directory: ansible
      run: |
        chmod +x generate_inventory.py
        ./generate_inventory.py > inventory.json

    - name: Run Linux Playbook
      working-directory: ansible
      run: |
        ansible-playbook -i inventory.json linux_playbook.yml

    - name: Run Windows Playbook
      working-directory: ansible
      run: |
        ansible-playbook -i inventory.json win_playbook.yml
